foodcollector/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),


]

main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    # path('new', views.new, name='new'),
    path('about/', views.about, name='about'),
    path('characters/', views.character_index, name='character-index'),
      path('character/<int:character_id>/add-gamesession',
         views.add_gamesession,
         name='add-gamesession'
         ),
    path('characters/<int:character_id>/', views.character_detail, name='character-detail'),
    path('characters/create/', views.CharacterCreate.as_view(), name='character-create'), 
    path('character/<int:pk>/update/', views.CharacterUpdate.as_view(), name='character-update'),
    path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name='character-delete'),
    path('location/create/', views.LocationCreate.as_view(), name='location-create'),
    path('location/<int:pk>/', views.LocationDetail.as_view(), name='location-detail'),
    path('location/', views.LocationList.as_view(), name='location-index'),
    path('location/<int:pk>/update/', views.LocationUpdate.as_view(), name='location-update'),
    path('location/<int:pk>/delete/', views.LocationDelete.as_view(), name='location-delete'),
    ]

main_app/models.py
from django.db import models
from django.urls import reverse

POWERUPS = (
    ('M', 'Mushrooms'),
    ('S', 'Shell'),
    ('F', 'Flower'),
    ('C', 'Carrot')
)

class Character(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    description = models.TextField(max_length=250)


    def __str__(self):
        return f' {self.name} ({self.id})'
    
    def get_absolute_url(self):
        return reverse("character-detail", kwargs={"character_id": self.id})
    
    
class GameSession(models.Model):
    date = models.DateField('Game Date')
    power_up = models.CharField(
        max_length=2,
        choices=POWERUPS,
        default=POWERUPS[0][0]
        )
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_power_up_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']
        

class Location(models.Model):
    name = models.CharField(max_length=50)
    challenge_level = models.CharField(max_length=20)
    def __str__(self):
            return self.name
    def get_absolute_url(self):
        return reverse("location-detail", kwargs={"pk": self.pk})
    
    

    
    

main_app/forms.py
from django import forms
from .models import GameSession, Location

class GameSessionForm(forms.ModelForm):
    class Meta:
        model = GameSession
        fields = ['date', 'power_up']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a Date',
                    'type': 'date'
                }
            ),
        }

main_app/views.py
from django.shortcuts import render, redirect
from .models import Character
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import GameSessionForm, Location



# Import HttpResponse to send text-based responses

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def character_index(request):
    characters = Character.objects.all()
    return render(request, 'characters/index.html', {'characters': characters})

def character_detail(request, character_id):
    character = Character.objects.get(id=character_id)
    gamesession_form = GameSessionForm()
    return render(request, 'characters/detail.html', {'character': character, 'gamesession_form': gamesession_form})

def add_gamesession(request, character_id):
    form = GameSessionForm(request.POST)
    if form.is_valid():
        new_gamesession = form.save(commit=False)
        new_gamesession.character_id = character_id
        new_gamesession.save()
    return redirect('character-detail', character_id=character_id)   

class CharacterCreate(CreateView):
    model = Character
    fields = '__all__'

class CharacterUpdate(UpdateView):
    model = Character
    fields = ['age', 'description']
    

class CharacterDelete(DeleteView):
    model = Character
    success_url='/characters/'
    
class LocationCreate(CreateView):
    model = Location
    fields = '__all__'

class LocationList(ListView):
    model = Location

class LocationDetail(DetailView):
    model = Location
    
    
class LocationUpdate(UpdateView):
    model = Location
    fields = ['name', 'challenge_level']
    
class LocationDelete(DeleteView):
    model = Location
    success_url = '/location/'

main_app/templates/about.html
{% extends "base.html" %}
{% block content %}
<p>I am practicing Django!</p>
{% endblock %}

main_app/templates/base.html
{%load  static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{%static 'images/People.png' %}" />
    <title>Mario characters</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />

    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="images/People.png" alt='marioworld'/>
        </a>
      </div>
      <nav>
        <ul>
          <li><a href="{% url 'character-index'%}">All Characters</a></li>
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'character-create'%}">Add a Character</a></li>
          <li><a href="{% url 'location-create'%}">Add a Location</a></li>
          <li><a href="{% url 'location-index'%}">All Locations</a></li>


        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

main_app/templates/characters/detail.html
{% extends 'base.html' %}
{%load static  %}
{%block head%}
<link rel="stylesheet" href="{% static 'css/characters/character-detail.css'%}" />
{%endblock%}
{%block content%}

<section class="character-container">
    <div class="character-img">
        <img src="{%static 'images/People.png'%}" alt="all Characters" />
    </div>
    <div class="character-detail">
        <h1>{{character.name}}</h1>
        {% if character.age < 35 %}
            <h2> {{character.name}} is {{character.age}} and is a younger character but dont underestimate them!
        {%else%}
                <h2> {{character.name}} is an OG character! </h2>
        {% endif %}
        <p>{{character.description}}</p>
        <div class='character-actions'>
            <a href="{% url 'character-update' character.id%}" class="btn warn">Edit</a>
            <a href="{% url 'character-delete' character.id%}" class="btn danger">Delete</a>
        </div>
    </div>
</section>


<!-- Existing cat-container above -->
<div class="gamesession-container">
  <section class="gamesession">
    <div class="subsection-title">
      <h2>Game Session</h2>
      <img
      src="{% static 'images/People.png' %}"
      alt="Mario Characters"
      />
      <img src="{% static 'images/dino.png' %}" alt="dino" />
      <img
      src="{% static 'images/donkey.png' %}"
      alt="donkey"
      />
    </div>

    <h3>Add a Game Session</h3> 
    <form 
      method="post" 
      class="subsection-content" 
      autocomplete="off"
      action="{% url 'add-gamesession' character.id %}">
      {% csrf_token %%}
      {{gamesession_form.as_p}}
      <button type="submit" class="btn submit"> Add Game Session</button>
    </form>
<h3> Past Feedings</h3>
{% if character.gamesession_set.all.count%}
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>PowerUp</th>
        </tr>
      </thead>
      <tbody>
        {% for gamesession in character.gamesession_set.all %}
        <tr>
          <td>{{gamesession.date}}</td>
          <td>{{gamesession.get_power_up_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      {%else%}
      <div class="subsection-content">
        <p>{{character.name}} has no game sessions </p>

      </div>
      {%endif%}
    </section>
  </div>
  
  {% endblock %}

            

main_app/templates/characters/index.html
{%extends 'base.html'%}
{%load static%}
{%block head %}
<link rel='stylesheet' href="{% static 'css/characters/character-index.css'%}"/>
{% endblock %}
{% block content %}

<section class="page-header">
    <h1> Character List</h1>
    <img src="{%static 'images/Mario.png' %}" alt='Mario'/>
    <img src="{%static 'images/Luigi.png' %}" alt='Luigi'/>
    <img src="{%static 'images/Toad.png' %}" alt='Toad'/>
    <img src="{%static 'images/Peach.png' %}" alt='Peach'/>
    <img src="{%static 'images/Bowser.png' %}" alt='Bowser'/>
    <img src="{%static 'images/Donkey.png' %}" alt='Donkey'/>
</section>
<section class='card-container'>
    {% for character in characters%}
    <div class='card'>
        <a href="{% url 'character-detail' character.id %}">
            <div class='card-content'>
                <div class='card-img-container'>
                    <img
                        src="{%static 'images/Dino.png' %}"
                        alt='dino'
                    />
                </div>
            <h2 class="card-title">{{character.name}}</h2>
            {%if character.age < 40 %}
            <p>{{character.name}} is {{character.description}} and {{character.age}} years old</p>
            {% else %}
            <p> {{character.name}} is an OG! and is {{character.age}} years old</p>
            {% endif %}
            <p>{{character.description}}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</section>
    
{%endblock%}

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel='stylesheet' href='{% static "css/home.css" %}}'
{% endblock %}
{% block content %}


<section class='logo-container'>
    <div class='character-container'>

    </div>

</section>

{%endblock%}

main_app/templates/main_app/character_confirm_delete.html
{%extends 'base.html'%}
{%load static%}
{% block content %}

<div class="page-header">
    <h1>Delete Character</h1>
</div>

<h2>Are you sure you want to delete {{character.name}}?</h2>
<form action="" method="post" class="form">
        {% csrf_token %}
    <a href="{% url 'character-detail' character.id %}" class="btn secondary"> Cancel </a>
    <button type="submit" class="btn danger"> Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/character_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 

{%block content%}
<div class="page-header">
    {% if character %}
    <h1>Edit {{ character.name }}</h1>
    {% else %}
    <h1>Add a Character</h1>
    {% endif %}
    <img src="{% static 'images/Dino.png' %}" alt="A Mario World Dinosaur" />
  </div>


<form action="" method="POST" class="form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>
{%endblock%}

main_app/templates/main_app/location_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Location?</h1>
 
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'location-detail' location.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/location_detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/location/location-detail.css' %}" />
{% endblock %} 
{% block content %}

<div class="card">
  <div class="card-bg"></div>
  <div class="card-content">
    <h2>{{ location.name }}</h2>
    <p>A {{ location.challenge_level }} Level</p>
  </div>
</div>
<a href="{%url 'location-update' location.id %}" class="btn warn">Edit</a>
<a href="{% url 'location-delete' location.id %}" class="btn danger">Delete</a>

{% endblock %}

main_app/templates/main_app/location_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add a Location</h1>
    {% endif %}
    <img src="{% static 'images/People.png' %}" alt="mario characters" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

main_app/templates/main_app/location_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/location/location-index.css' %}" />
{% endblock %} 
{% block content %}

<section class="page-header">
  <h1>All Locations</h1>
  {% comment %} <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
  <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
  <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
  <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" /> {% endcomment %}
</section>

<section class="card-container">
  {% for location in location_list %}
    <div class="card">
      <div class="card-bg"></div>
      <a href="{% url 'location-detail' location.id %}">
        <div class="card-content">
          <h2>{{ location.name }}</h2>
          <p>{{ location.challenge_level }} is this challenge Level</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}